{"uuid":"0f81286f-785e-496f-94bf-cb13441a2c7c","historyId":"e54a198a960d1203ef9888505154c1ba","fullName":"com.qacart.todo.testcases.TodoTest.CheckFunctionalityOfAddTask","labels":[{"name":"package","value":"com.qacart.todo.testcases.TodoTest"},{"name":"testClass","value":"com.qacart.todo.testcases.TodoTest"},{"name":"testMethod","value":"CheckFunctionalityOfAddTask"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"TodoApplicationProject"},{"name":"subSuite","value":"com.qacart.todo.testcases.TodoTest"},{"name":"host","value":"DESKTOP-KCILITF"},{"name":"thread","value":"23628@DESKTOP-KCILITF.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Add Todo"},{"name":"feature","value":"Todo feature"}],"links":[],"name":"CheckFunctionalityOfAddTask","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [New Task Today] but found [My first task]","trace":"java.lang.AssertionError: expected [New Task Today] but found [My first task]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat com.qacart.todo.testcases.TodoTest.CheckFunctionalityOfAddTask(TodoTest.java:44)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n\tat org.testng.TestRunner.run(TestRunner.java:621)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","steps":[{"name":"load","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1700945035197,"stop":1700945037106},{"name":"load","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1700945037141,"stop":1700945037624},{"name":"addTask","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"taskName","value":"My first task"}],"start":1700945037626,"stop":1700945037877}],"attachments":[],"parameters":[],"start":1700945031364,"stop":1700945038323}